"""Initial migration

Revision ID: 6f44ce82332b
Revises: 
Create Date: 2026-04-14 00:35:47.733481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f44ce82332b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Market', 'market_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Market', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('Market', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('MarketCategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('MarketCategory', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('MonthReference', 'month_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('MonthReference', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('MonthReference', 'days_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('TimePeriod', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('TimePeriod', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(op.f('uq_year_month'), 'TimePeriod', type_='unique')
    op.drop_constraint(None, 'TimePeriod', type_='foreignkey')
    op.alter_column('VisitorArrival', 'arrival_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('VisitorArrival', 'created_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(op.f('uq_market_period'), 'VisitorArrival', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_market_period'), 'VisitorArrival', ['market_id', 'period_id'])
    op.alter_column('VisitorArrival', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('VisitorArrival', 'arrival_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_foreign_key(None, 'TimePeriod', 'MonthReference', ['month'], ['month_number'])
    op.create_unique_constraint(op.f('uq_year_month'), 'TimePeriod', ['year', 'month'])
    op.alter_column('TimePeriod', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('TimePeriod', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('MonthReference', 'days_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('MonthReference', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('MonthReference', 'month_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('MarketCategory', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('MarketCategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('Market', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('Market', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('Market', 'market_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###